[package]
name = "liquesco-gen-schema"
version = "0.0.1"
authors = ["cronosun"]
edition = "2018"

[dependencies]
liquesco-common = { path = "../common" }
liquesco-gen-html = { path = "../gen-html" }
liquesco-schema = { path = "../schema" }
liquesco-processing = { path = "../processing" }
