[package]
name = "rust"
version = "0.1.0"
authors = ["cronosun <simon.ruoss@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.1"
enum-repr = "0.2.4"
integer-encoding = "1.0.5"
decimal = "2.0.4"
