[workspace]
# Note: Currently only the "core" modules activated. Other modules beging refactored.
members = ["common", "serialization", "schema"]
#members = ["common", "serialization", "schema", "parsing", "processing", "gen-html", "gen-schema"]
