[package]
name = "liquesco-common"
version = "0.0.1"
authors = ["cronosun <simon.ruoss@gmail.com>"]
edition = "2018"

[dependencies]
serde = {version = "1.0.91", features = ["derive"]}
derive_more = "0.13.0"
derive-new = "0.5"




